<?php
namespace AdminBundle\Repository;
use Framework\Component\ORM\Repository;

class Import extends Repository{

    function findBy($criteria = array())
    {
        return parent::findBy($criteria); // TODO: Change the autogenerated stub
    }
}